ping-item: '@'

player-name-color: 'YELLOW'

ping-message:
  enable: true
  message: '&a%sender% Pinged you, %player%!'

ping-actionbar:
  enable: true
  actionbar: '&a%sender% Pinged you, %player%!'

ping-title:
  enable: true
  title: '&a%sender% Pinged you, %player%!'
  sub-title: '&a%sender% Pinged you, %player%!'
  fade-in: 20
  show-time: 60
  fade-out: 20

#You can find all sounds here!
#https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
ping-sound:
  enable: true
  sound: 'ENTITY_PLAYER_LEVELUP'