tag-item: '@'

player-name-color: 'YELLOW'

ping-message:
  enable: true
  message: '&a%sender% Pinged you, %player%!'

ping-sound:
  enable: true
  sound: ''

ping-actionbar:
  enable: true
  actionbar: '&a%sender% Pinged you, %player%!'

ping-title:
  enable: true
  title: '&a%sender% Pinged you, %player%!'
  sub-title: '&a%sender% Pinged you, %player%!'