name: Ping
version: ${project.version}
main: io.github.portlek.ping.Ping
authors: [portlek]
description: Tag and ping a player.
website: https://www.github.com/portlek

permissions:
  ping.use:
    description: Allows you ping a player
    default: true